version: '3.1'

services:
  mongo:
    image: mongo:3.6-stretch
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /tmp/mongodb:/data/db
      - .:/app
    ports:
      - "27017:27017"
